import { Link } from "react-router-dom";
import Wordmark from "../components/Wordmark";
import MarketingFooter from "../components/MarketingFooter";
import {
  BookIcon,
  CupIcon,
  HeartIcon,
  LeafIcon,
  MoonIcon,
  SunIcon,
} from "../components/icons";

export default function Terms() {
  return (
    <div className="app landing">
      <header className="app-header app-header--landing">
        <div className="wrap">
          <Wordmark />
          <nav className="nav-links nav-links--landing" aria-label="Menu">
            <Link to="/pricing" className="nav-link">
              Pricing
            </Link>
            <Link to="/" className="btn btn--ghost btn--sm">
              Back
            </Link>
          </nav>
        </div>
      </header>

      <main className="app-main">
        <div className="privacy">
          <div className="privacy-head">
            <span className="head-eyebrow">
              <BookIcon size={13} />
              Terms of service
            </span>
            <h1>Terms of Service</h1>
            <p className="privacy-lead">
              Plain words about how Small Steps works. This is a gentle service
              with a real price tag on one option — so the terms are kept short
              and honest.
            </p>
          </div>

          <div className="privacy-grid">
            <section className="privacy-card spot-card">
              <span className="privacy-card-icon">
                <LeafIcon size={16} />
              </span>
              <h2>The service</h2>
              <p>
                Small Steps is a private journal with one warm reply after each
                entry. There are no streaks, no scores, and no quotas — the
                pace is always yours. We run on the free plan, forever, and on
                a paid option called Private.
              </p>
            </section>

            <section className="privacy-card spot-card">
              <span className="privacy-card-icon">
                <HeartIcon size={16} />
              </span>
              <h2>Your journal belongs to you</h2>
              <p>
                Everything you write is yours. We store it only to run the
                service, and you can edit, delete, or export any of it at any
                time. If you ask us to remove your account and data, we will.
              </p>
            </section>

            <section className="privacy-card spot-card">
              <span className="privacy-card-icon">
                <SunIcon size={16} />
              </span>
              <h2>Replies are written by AI</h2>
              <p>
                Each reply is generated by Google's Gemini API. It can be
                imperfect, occasionally wrong, or miss the moment. It's a warm
                sounding board — not a person, and never a guarantee.
              </p>
            </section>

            <section className="privacy-card spot-card">
              <span className="privacy-card-icon">
                <MoonIcon size={16} />
              </span>
              <h2>Not medical advice</h2>
              <p>
                Small Steps is not a medical, therapeutic, or crisis service.
                It can't diagnose, treat, or replace professional care. If
                you're in crisis or considering self-harm, please reach out to
                a professional or a local emergency line.
              </p>
            </section>

            <section className="privacy-card spot-card" id="refunds">
              <span className="privacy-card-icon">
                <CupIcon size={16} />
              </span>
              <h2>Payments &amp; Private</h2>
              <p>
                Private costs ${"48"} once a year — a one-time transfer, not a
                subscription. Paying it turns on private AI processing, gentle
                daily reminders, and weekly notes for twelve months. When the
                year passes, you can quietly renew or stay on the free plan.
              </p>
            </section>

            <section className="privacy-card spot-card">
              <span className="privacy-card-icon">
                <LeafIcon size={16} />
              </span>
              <h2>Refunds</h2>
              <p>
                If Private isn't what you expected, write to us within 14 days
                of paying — before the first week of use — and we'll return
                your payment, no questions asked. After that, Private is
                non-refundable for the year, but you can stop using it anytime
                and stay on the free plan.
              </p>
            </section>

            <section className="privacy-card spot-card">
              <span className="privacy-card-icon">
                <HeartIcon size={16} />
              </span>
              <h2>What we ask in return</h2>
              <p>
                Please don't use Small Steps to store illegal material, harass
                people, or automate anything harmful. One account is yours
                alone — don't let others use it, and tell us if something
                looks wrong.
              </p>
            </section>

            <section className="privacy-card spot-card">
              <span className="privacy-card-icon">
                <BookIcon size={16} />
              </span>
              <h2>Ending things</h2>
              <p>
                You can delete your journal and stop using Small Steps anytime.
                We may suspend an account that clearly breaks these terms. If
                we ever change them, we'll say so plainly on this page before
                they take effect.
              </p>
            </section>
          </div>

          <div className="privacy-contact spot-card">
            <p>
              Questions about these terms or a refund?{" "}
              <a href="mailto:hello@smallsteps.app">hello@smallsteps.app</a>
            </p>
          </div>

          <p className="privacy-back">
            <Link to="/">Back to Small Steps</Link>
          </p>
        </div>
      </main>

      <MarketingFooter />
    </div>
  );
}